#!/usr/bin/env python3
"""
Generate .env from Terraform outputs and tfvars.

Usage:
    python3 gen-env.py <terraform.tfvars> <tf-output.json> <out-.env>
"""
import json
import re
import sys


def parse_tfvars(path: str) -> dict:
    """Extract key = "value" pairs from a tfvars file."""
    result = {}
    with open(path) as f:
        for line in f:
            m = re.match(r'^\s*(\w+)\s*=\s*"([^"]*)"', line)
            if m:
                result[m.group(1)] = m.group(2)
    return result


def val(outputs: dict, key: str) -> str:
    return outputs.get(key, {}).get("value") or ""


def main():
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <terraform.tfvars> <tf-output.json> <out-.env>")
        sys.exit(1)

    tfvars_path, tf_out_path, env_path = sys.argv[1], sys.argv[2], sys.argv[3]

    tfvars = parse_tfvars(tfvars_path)
    outputs = json.load(open(tf_out_path))

    cluster_id   = val(outputs, "kafka_cluster_id")
    kafka_key    = val(outputs, "kafka_api_key_id")
    kafka_secret = val(outputs, "kafka_api_key_secret")

    lines = [
        "# Generated by: make gen-env  —  do not commit",
        f"LINEAGE_BRIDGE_CONFLUENT_CLOUD_API_KEY={tfvars.get('confluent_cloud_api_key', '')}",
        f"LINEAGE_BRIDGE_CONFLUENT_CLOUD_API_SECRET={tfvars.get('confluent_cloud_api_secret', '')}",
        f'LINEAGE_BRIDGE_CLUSTER_CREDENTIALS={{"{cluster_id}":{{"api_key":"{kafka_key}","api_secret":"{kafka_secret}"}}}}',
        f"LINEAGE_BRIDGE_SCHEMA_REGISTRY_ENDPOINT={val(outputs, 'schema_registry_rest_endpoint')}",
        f"LINEAGE_BRIDGE_SCHEMA_REGISTRY_API_KEY={val(outputs, 'schema_registry_api_key_id')}",
        f"LINEAGE_BRIDGE_SCHEMA_REGISTRY_API_SECRET={val(outputs, 'schema_registry_api_key_secret')}",
        f"LINEAGE_BRIDGE_FLINK_API_KEY={val(outputs, 'flink_api_key_id')}",
        f"LINEAGE_BRIDGE_FLINK_API_SECRET={val(outputs, 'flink_api_key_secret')}",
        f"LINEAGE_BRIDGE_TABLEFLOW_API_KEY={val(outputs, 'tableflow_api_key_id')}",
        f"LINEAGE_BRIDGE_TABLEFLOW_API_SECRET={val(outputs, 'tableflow_api_key_secret')}",
        "LINEAGE_BRIDGE_LOG_LEVEL=INFO",
    ]

    with open(env_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"  Written to {env_path}")


if __name__ == "__main__":
    main()
